language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - master

install:
 - go get -u github.com/stretchr/testify/require github.com/jonboulle/clockwork github.com/russellhaering/jsonmap golang.org/x/text/unicode/norm golang.org/x/net/idna gopkg.in/dgrijalva/jwt-go.v2 gopkg.in/ldap.v2
