package validators

import (
	"testing"
	"time"

	"github.com/jonboulle/clockwork"
	"github.com/stretchr/testify/require"
)

func TestCert(t *testing.T) {
	valid := "-----BEGIN CERTIFICATE-----\nMIIC9DCCAl2gAwIBAgIJAJlgz00T2/3QMA0GCSqGSIb3DQEBCwUAMIGSMQswCQYD\nVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEMMAoGA1UEBwwDU0ZPMRQwEgYD\nVQQKDAtleGFtcGxlLmNvbTENMAsGA1UECwwEbGRhcDEZMBcGA1UEAwwQbGRhcC5l\neGFtcGxlLmNvbTEgMB4GCSqGSIb3DQEJARYRYWRtaW5AZXhhbXBsZS5jb20wHhcN\nMTYxMDA4MDE1MzAwWhcNMjYxMDA2MDE1MzAwWjCBkjELMAkGA1UEBhMCVVMxEzAR\nBgNVBAgMCkNhbGlmb3JuaWExDDAKBgNVBAcMA1NGTzEUMBIGA1UECgwLZXhhbXBs\nZS5jb20xDTALBgNVBAsMBGxkYXAxGTAXBgNVBAMMEGxkYXAuZXhhbXBsZS5jb20x\nIDAeBgkqhkiG9w0BCQEWEWFkbWluQGV4YW1wbGUuY29tMIGfMA0GCSqGSIb3DQEB\nAQUAA4GNADCBiQKBgQCjSAOofjzzzCjk7G813v0Faa2xUfPBQP34Aqlln71xND+H\nGOicg81/pxnOFD1qtns1ZYjq6nTXZ4E+xxAT2FMT+g9xeArYJgnZhTsI6WpFY8aK\nc1pgSUFDHY0C6tbtv0f/iZu9ZBhisELDKAhuqEIbCG2T/zZOOqwuHM3ARWpLiQID\nAQABo1AwTjAdBgNVHQ4EFgQUTIDPZ/9Es1p3GEelYBYh4peBGN8wHwYDVR0jBBgw\nFoAUTIDPZ/9Es1p3GEelYBYh4peBGN8wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0B\nAQsFAAOBgQBrVA7qwIk77Dcf2gvrcKVYIi+l/nkojLPg767r1ujWMwlYyHNBrl5p\nIX8C9MeO3LJKSFA0L1sZfyfpI+Rl0MtE0QupyfwO9a138xLolYJk05593mgbhV+U\niqCP7HKgTnHV9rioIfivHu7wUOPpgKZ8E3c8rarZiqUUGeejEtd5nw==\n-----END CERTIFICATE-----"

	v := X509CertificateValidator{clockwork.NewFakeClockAt(time.Now())}
	_, err := v.Validate(valid)
	require.NoError(t, err)

}
